# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LHvl7B9cVXiMlbGgZ-0Azt64gLyKzu1l
"""

!pip install diffusers transformers accelerate torch Pillow -q
!pip install streamlit -q
!pip install librosa soundfile -q
!pip install pyngrok -q
!pip install openai-whisper -q
!pip install audio-recorder-streamlit -q
!pip install streamlit-extras -q
!apt-get install -y ffmpeg -q

print("✅ All dependencies installed.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import torch
# import librosa
# import librosa.display
# import numpy as np
# import soundfile as sf
# import matplotlib
# matplotlib.use("Agg")
# import matplotlib.pyplot as plt
# import whisper
# import os
# import io
# import time
# import json
# import tempfile
# from PIL import Image, ImageDraw
# from diffusers import StableDiffusionPipeline
# from audio_recorder_streamlit import audio_recorder
# 
# # ─── Page Config ──────────────────────────────────────────────
# st.set_page_config(
#     page_title="PawCoach · AI Dog Trainer",
#     page_icon="🐾",
#     layout="wide",
#     initial_sidebar_state="expanded",
# )
# 
# # ─── Custom CSS ───────────────────────────────────────────────
# st.markdown("""
# <style>
# @import url('https://fonts.googleapis.com/css2?family=Syne:wght@700;800&family=DM+Sans:wght@400;500&display=swap');
# 
# html, body, [class*="css"] {
#     font-family: 'DM Sans', sans-serif;
#     background-color: #0e1117;
#     color: #f0ede8;
# }
# h1, h2, h3 { font-family: 'Syne', sans-serif; }
# 
# .pawcard {
#     background: #1a1f2e;
#     border: 1px solid #2a3040;
#     border-radius: 16px;
#     padding: 24px;
#     margin-bottom: 20px;
# }
# .score-box {
#     background: linear-gradient(135deg, #1e3a2f, #0e1117);
#     border: 1px solid #2ecc71;
#     border-radius: 12px;
#     padding: 16px;
#     text-align: center;
# }
# .score-num {
#     font-family: 'Syne', sans-serif;
#     font-size: 3rem;
#     font-weight: 800;
#     color: #2ecc71;
# }
# .feedback-good { color: #2ecc71; font-weight: 500; }
# .feedback-warn { color: #f39c12; font-weight: 500; }
# .feedback-bad  { color: #e74c3c; font-weight: 500; }
# .panel-label {
#     background: #2a3040;
#     border-radius: 8px;
#     padding: 4px 10px;
#     font-size: 0.75rem;
#     font-family: 'Syne', sans-serif;
#     letter-spacing: 0.08em;
#     text-transform: uppercase;
# }
# div[data-testid="stSidebar"] {
#     background: #13161f;
#     border-right: 1px solid #2a3040;
# }
# .stButton > button {
#     background: #2ecc71;
#     color: #0e1117;
#     font-family: 'Syne', sans-serif;
#     font-weight: 700;
#     border: none;
#     border-radius: 10px;
#     padding: 10px 24px;
#     letter-spacing: 0.04em;
# }
# .stButton > button:hover {
#     background: #27ae60;
#     color: #fff;
# }
# .stTabs [data-baseweb="tab"] {
#     font-family: 'Syne', sans-serif;
#     font-weight: 700;
#     font-size: 0.9rem;
# }
# </style>
# """, unsafe_allow_html=True)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile -a app.py
# 
# # ─── Dog Command Science Standards ───────────────────────────
# # Based on animal behavior research on effective verbal cues.
# # Pryor (2009), Hiby et al. (2004), and professional LIMA trainer guidelines.
# 
# COMMAND_STANDARDS = {
#     "Sit":   {"duration_max": 1.2, "pitch_drop": True, "volume_min": 60, "label": "Sit"},
#     "Stay":  {"duration_max": 1.5, "pitch_drop": True, "volume_min": 58, "label": "Stay"},
#     "Come":  {"duration_max": 1.0, "pitch_drop": False,"volume_min": 62, "label": "Come"},
#     "Down":  {"duration_max": 1.2, "pitch_drop": True, "volume_min": 60, "label": "Down"},
#     "Leave it": {"duration_max": 1.8,"pitch_drop": True, "volume_min": 63,"label": "Leave it"},
#     "Drop it": {"duration_max": 1.5,"pitch_drop": True, "volume_min": 60, "label": "Drop it"},
#     "Heel":  {"duration_max": 1.0, "pitch_drop": True, "volume_min": 58, "label": "Heel"},
# }
# 
# # ─── Image Generation Config ──────────────────────────────────
# PANEL_TEMPLATES = {
#     1: (
#         "A {dog_color} {dog_breed} dog and an {trainer} standing together "
#         "on a {environment}, preparing for {command} training. "
#         "Realistic photo, natural light."
#     ),
#     2: (
#         "An {trainer} giving a clear hand signal to a {dog_color} {dog_breed} dog "
#         "on a {environment}, demonstrating the {command} command. Realistic photo."
#     ),
#     3: (
#         "A {dog_color} {dog_breed} dog performing the {command} command correctly "
#         "on a {environment}, ears forward, attentive. Realistic photo."
#     ),
#     4: (
#         "An {trainer} kneeling down giving a treat to a {dog_color} {dog_breed} dog "
#         "on a {environment}, the dog sitting obediently. "
#         "Positive reinforcement dog training. Realistic photo."
#     ),
# }
# PANEL_LABELS = {
#     1: "Step 1 · Setup",
#     2: "Step 2 · Signal",
#     3: "Step 3 · Execute",
#     4: "Step 4 · Reward",
# }
# NEGATIVE_PROMPT = (
#     "blurry, deformed, extra limbs, bad anatomy, low quality, "
#     "cartoon, anime, painting, watermark, text, ugly, nsfw"
# )
# 
# # ─── Emotion Recognition Config ───────────────────────────────
# # Maps (context, acoustic_cluster) → emotion label + advice
# BARK_EMOTIONS = {
#     ("excitement", "high_freq_fast"): {
#         "emotion": "Excited / Playful 🎾",
#         "confidence": "High",
#         "advice": "Your dog is in a great mood! Perfect time for play-based training."
#     },
#     ("excitement", "high_freq_slow"): {
#         "emotion": "Happy / Content 😊",
#         "confidence": "Medium",
#         "advice": "Relaxed positive state. Good moment to introduce new commands."
#     },
#     ("alert", "high_freq_fast"): {
#         "emotion": "Alert / Territorial 🔔",
#         "confidence": "High",
#         "advice": "Dog senses something unusual. Redirect attention before training."
#     },
#     ("alert", "low_freq_slow"): {
#         "emotion": "Anxious / Wary 😟",
#         "confidence": "Medium",
#         "advice": "Your dog feels uneasy. Remove the stressor before any training session."
#     },
#     ("distress", "low_freq_fast"): {
#         "emotion": "Distressed / Fearful 😨",
#         "confidence": "High",
#         "advice": "Do NOT train now. Comfort your dog first. Check for pain or threat."
#     },
#     ("distress", "high_freq_slow"): {
#         "emotion": "Seeking Attention 🐾",
#         "confidence": "Medium",
#         "advice": "Dog wants interaction. Engage briefly, then channel into a training game."
#     },
#     ("play", "high_freq_fast"): {
#         "emotion": "Play-soliciting 🏃",
#         "confidence": "High",
#         "advice": "Excellent training window! Use play as the reward today."
#     },
#     ("calm", "low_freq_slow"): {
#         "emotion": "Calm / Bored 😴",
#         "confidence": "Medium",
#         "advice": "Low arousal. Use high-value treats to build engagement before drilling commands."
#     },
# }
# DEFAULT_BARK_RESULT = {
#     "emotion": "Uncertain 🤔",
#     "confidence": "Low",
#     "advice": "Unclear signal. Describe the context more specifically for a better reading."
# }

# Commented out IPython magic to ensure Python compatibility.
# %%writefile -a app.py
# 
# # ─── Image Generation via Pollinations.ai (Free, No API Key) ──
# 
# import requests as _req
# import urllib.parse
# import io as _io
# import time as _time
# 
# def load_sd_pipeline():
#     return None
# 
# def generate_panel(pipe, prompt, seed):
#     """
#     Generate images via Pollinations.ai with automatic retries (handles 429 rate limiting).
#     """
#     encoded_prompt = urllib.parse.quote(prompt)
#     url = (
#         f"https://image.pollinations.ai/prompt/{encoded_prompt}"
#         f"?width=512&height=512&seed={seed}&nologo=true&model=flux"
#     )
# 
#     for attempt in range(5):  # Retry up to 5 times
#         try:
#             resp = _req.get(url, timeout=90)
#             if resp.status_code == 200:
#                 return Image.open(_io.BytesIO(resp.content)).convert("RGB")
#             elif resp.status_code == 429:
#                 wait = 8 + attempt * 5  # 8s, 13s, 18s, 23s, 28s
#                 _time.sleep(wait)
#                 continue
#             else:
#                 _time.sleep(5)
#                 continue
#         except Exception:
#             _time.sleep(8)
#             continue
# 
#     # Return placeholder image if all retries fail
#     img = Image.new("RGB", (512, 512), (30, 35, 50))
#     draw = ImageDraw.Draw(img)
#     draw.text((256, 256), "Generation Failed\nTry Again", fill=(200,200,200), anchor="mm")
#     return img
# 
# def build_prompts(dog_breed, dog_color, trainer, environment, command):
#     """
#     4 images correspond to: Preparation → Giving Command → Dog Performing → Reward.
#     Each prompt emphasizes a continuous story feel.
#     """
#     return {
#         1: (
#             f"A {dog_color} {dog_breed} dog and a {trainer} standing together "
#             f"on a {environment}, relaxed, making eye contact, preparing for training. "
#             f"Bright natural light, photorealistic, 4K."
#         ),
#         2: (
#             f"A {trainer} standing upright on a {environment}, "
#             f"pointing finger down and saying '{command}' command clearly, "
#             f"a {dog_color} {dog_breed} dog looking up attentively. "
#             f"Training hand signal, photorealistic, 4K."
#         ),
#         3: (
#             f"A {dog_color} {dog_breed} dog successfully performing the '{command}' command "
#             f"on a {environment}, sitting/responding perfectly, ears forward, focused. "
#             f"The {trainer} watching proudly. Photorealistic, 4K."
#         ),
#         4: (
#             f"A {trainer} kneeling down, smiling warmly, giving a treat to "
#             f"a {dog_color} {dog_breed} dog on a {environment}. "
#             f"The dog sits obediently, tail wagging, positive reinforcement moment. "
#             f"Warm light, photorealistic, 4K."
#         ),
#     }
# 
# def make_grid(images):
#     W, H = 512, 512
#     pad = 12
#     label_h = 32
#     cols = 4
#     total_w = W * cols + pad * (cols + 1)
#     total_h = label_h + H + pad * 2
#     grid = Image.new("RGB", (total_w, total_h), (20, 24, 36))
#     draw = ImageDraw.Draw(grid)
#     for i, img in enumerate(images):
#         x = pad + i * (W + pad)
#         y = label_h
#         label = PANEL_LABELS[i + 1]
#         draw.text((x + W // 2, label_h // 2), label,
#                   fill=(180, 180, 200), anchor="mm")
#         grid.paste(img, (x, y))
#     return grid

# Commented out IPython magic to ensure Python compatibility.
# %%writefile -a app.py
# 
# # ─── Voice Analysis ───────────────────────────────────────────
# 
# @st.cache_resource(show_spinner=False)
# def load_whisper():
#     return whisper.load_model("base")
# 
# def analyze_voice(audio_bytes, command_key):
#     """
#     Analyze recorded voice command against science-based standards.
#     Returns a dict with scores and feedback for each dimension.
#     """
#     std = COMMAND_STANDARDS.get(command_key, COMMAND_STANDARDS["Sit"])
# 
#     # Save bytes to temp file
#     with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
#         f.write(audio_bytes)
#         tmp_path = f.name
# 
#     try:
#         y, sr = librosa.load(tmp_path, sr=None)
#     except Exception:
#         return None
#     finally:
#         os.unlink(tmp_path)
# 
#     results = {}
# 
#     # ── 1. Duration ────────────────────────────────────────────
#     duration = librosa.get_duration(y=y, sr=sr)
#     results["duration"] = {
#         "value": round(duration, 2),
#         "target": f"< {std['duration_max']}s",
#         "pass": duration <= std["duration_max"],
#         "feedback": (
#             f"✅ Great — command was sharp at {duration:.2f}s."
#             if duration <= std["duration_max"]
#             else f"⚠️ Too long ({duration:.2f}s). Aim for under {std['duration_max']}s. Short commands are clearer for dogs."
#         ),
#     }
# 
#     # ── 2. Volume / RMS ────────────────────────────────────────
#     rms = librosa.feature.rms(y=y)[0]
#     avg_rms = float(np.mean(rms))
#     # Convert to approximate dB SPL proxy (relative)
#     db_proxy = 20 * np.log10(avg_rms + 1e-9) + 90  # shifted to ~dB range
#     vol_pass = db_proxy >= std["volume_min"]
#     results["volume"] = {
#         "value": round(db_proxy, 1),
#         "target": f">= {std['volume_min']} dB",
#         "pass": vol_pass,
#         "feedback": (
#             f"✅ Good volume ({db_proxy:.1f} dB) — assertive and clear."
#             if vol_pass
#             else f"⚠️ Too quiet ({db_proxy:.1f} dB). Speak more firmly — dogs respond to confident volume."
#         ),
#     }
# 
#     # ── 3. Pitch Contour (does tone drop at end?) ──────────────
#     pitches, magnitudes = librosa.piptrack(y=y, sr=sr)
#     pitch_vals = []
#     for t in range(pitches.shape[1]):
#         idx = magnitudes[:, t].argmax()
#         p = pitches[idx, t]
#         if p > 80:
#             pitch_vals.append(p)
# 
#     if len(pitch_vals) >= 6:
#         first_half = np.mean(pitch_vals[:len(pitch_vals)//2])
#         second_half = np.mean(pitch_vals[len(pitch_vals)//2:])
#         pitch_drops = second_half < first_half
#     else:
#         pitch_drops = False
# 
#     if std["pitch_drop"]:
#         pitch_pass = pitch_drops
#         feedback_pitch = (
#             "✅ Pitch drops at the end — authoritative and clear for your dog."
#             if pitch_pass
#             else "❌ Pitch rises at the end (like a question). Dogs interpret rising tone as uncertain. Keep it flat or downward."
#         )
#     else:
#         # For "Come" — slightly rising/excited tone is OK
#         pitch_pass = True
#         feedback_pitch = "✅ Pitch contour is appropriate for this command."
# 
#     results["pitch"] = {
#         "value": "drops" if pitch_drops else "rises",
#         "target": "drops" if std["pitch_drop"] else "any",
#         "pass": pitch_pass,
#         "feedback": feedback_pitch,
#     }
# 
#     # ── 4. Clarity via Whisper transcription ──────────────────
#     whisper_model = load_whisper()
#     with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
#         sf.write(f.name, y, sr)
#         tmp2 = f.name
#     try:
#         result = whisper_model.transcribe(tmp2, language="en")
#         transcript = result["text"].strip().lower()
#     except Exception:
#         transcript = ""
#     finally:
#         os.unlink(tmp2)
# 
#     expected = command_key.lower()
#     clarity_pass = expected in transcript
#     results["clarity"] = {
#         "value": transcript or "(not detected)",
#         "target": command_key,
#         "pass": clarity_pass,
#         "feedback": (
#             f"✅ Command recognized clearly: \"{transcript}\""
#             if clarity_pass
#             else f"⚠️ Detected: \"{transcript or 'nothing'}\". Enunciate '{command_key}' more clearly."
#         ),
#     }
# 
#     # ── Overall Score ──────────────────────────────────────────
#     passed = sum(1 for v in results.values() if v["pass"])
#     total = len(results)
#     score = int((passed / total) * 100)
# 
#     # ── Waveform plot ─────────────────────────────────────────
#     fig, axes = plt.subplots(2, 1, figsize=(8, 4), facecolor="#0e1117")
#     ax1, ax2 = axes
# 
#     # Waveform
#     ax1.plot(np.linspace(0, duration, len(y)), y, color="#2ecc71", linewidth=0.8, alpha=0.9)
#     ax1.set_facecolor("#1a1f2e")
#     ax1.set_ylabel("Amplitude", color="#aaa", fontsize=9)
#     ax1.tick_params(colors="#aaa")
#     ax1.set_title("Waveform", color="#f0ede8", fontsize=10, pad=4)
#     for spine in ax1.spines.values():
#         spine.set_edgecolor("#2a3040")
# 
#     # Pitch over time
#     if len(pitch_vals) > 0:
#         ax2.plot(pitch_vals, color="#f39c12", linewidth=1.2)
#         ax2.set_facecolor("#1a1f2e")
#         ax2.set_ylabel("Pitch (Hz)", color="#aaa", fontsize=9)
#         ax2.set_title("Pitch Contour", color="#f0ede8", fontsize=10, pad=4)
#         ax2.tick_params(colors="#aaa")
#         for spine in ax2.spines.values():
#             spine.set_edgecolor("#2a3040")
#     else:
#         ax2.text(0.5, 0.5, "Pitch not detected", ha="center", va="center",
#                  color="#aaa", transform=ax2.transAxes)
#         ax2.set_facecolor("#1a1f2e")
# 
#     plt.tight_layout(pad=1.5)
#     buf = io.BytesIO()
#     plt.savefig(buf, format="png", bbox_inches="tight", facecolor="#0e1117")
#     buf.seek(0)
#     plt.close()
# 
#     return {"score": score, "results": results, "plot": buf}

# Commented out IPython magic to ensure Python compatibility.
# %%writefile -a app.py
# 
# # ─── Bark Emotion Recognition ────────────────────────────────
# 
# def classify_bark_acoustics(y, sr):
#     """
#     Classify bark acoustic cluster from audio features.
#     Returns one of: high_freq_fast, high_freq_slow, low_freq_fast, low_freq_slow
#     """
#     # Spectral centroid → proxy for perceived pitch
#     centroid = librosa.feature.spectral_centroid(y=y, sr=sr)[0]
#     avg_centroid = float(np.mean(centroid))
# 
#     # Onset rate → proxy for speed/tempo
#     onset_frames = librosa.onset.onset_detect(y=y, sr=sr)
#     duration = librosa.get_duration(y=y, sr=sr)
#     onset_rate = len(onset_frames) / max(duration, 0.1)  # onsets per second
# 
#     freq_class = "high_freq" if avg_centroid > 2000 else "low_freq"
#     speed_class = "fast" if onset_rate > 2.0 else "slow"
# 
#     return f"{freq_class}_{speed_class}", avg_centroid, onset_rate
# 
# def analyze_bark(audio_bytes, context_key):
#     """
#     Multi-modal bark emotion analysis:
#     - Audio: spectral centroid + onset rate
#     - Context: user-provided situation description
#     Returns emotion label + advice + feature values.
#     """
#     with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
#         f.write(audio_bytes)
#         tmp_path = f.name
# 
#     try:
#         y, sr = librosa.load(tmp_path, sr=None)
#     except Exception:
#         return None
#     finally:
#         os.unlink(tmp_path)
# 
#     acoustic_cluster, centroid, onset_rate = classify_bark_acoustics(y, sr)
#     lookup_key = (context_key, acoustic_cluster)
#     emotion_result = BARK_EMOTIONS.get(lookup_key, DEFAULT_BARK_RESULT)
# 
#     # Build spectrogram plot
#     fig, axes = plt.subplots(1, 2, figsize=(10, 3.5), facecolor="#0e1117")
# 
#     # Mel spectrogram
#     S = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=64)
#     S_db = librosa.power_to_db(S, ref=np.max)
#     img = librosa.display.specshow(S_db, sr=sr, x_axis="time", y_axis="mel",
#                                    ax=axes[0], cmap="magma")
#     axes[0].set_title("Mel Spectrogram", color="#f0ede8", fontsize=10)
#     axes[0].set_facecolor("#1a1f2e")
#     axes[0].tick_params(colors="#aaa")
#     axes[0].yaxis.label.set_color("#aaa")
#     axes[0].xaxis.label.set_color("#aaa")
#     for sp in axes[0].spines.values():
#         sp.set_edgecolor("#2a3040")
# 
#     # Onset strength
#     onset_env = librosa.onset.onset_strength(y=y, sr=sr)
#     times = librosa.times_like(onset_env, sr=sr)
#     axes[1].plot(times, onset_env, color="#e74c3c", linewidth=1.2)
#     axes[1].set_facecolor("#1a1f2e")
#     axes[1].set_title("Bark Energy / Onset Strength", color="#f0ede8", fontsize=10)
#     axes[1].tick_params(colors="#aaa")
#     for sp in axes[1].spines.values():
#         sp.set_edgecolor("#2a3040")
# 
#     plt.tight_layout(pad=1.5)
#     buf = io.BytesIO()
#     plt.savefig(buf, format="png", bbox_inches="tight", facecolor="#0e1117")
#     buf.seek(0)
#     plt.close()
# 
#     return {
#         "emotion": emotion_result["emotion"],
#         "confidence": emotion_result["confidence"],
#         "advice": emotion_result["advice"],
#         "acoustic_cluster": acoustic_cluster,
#         "centroid_hz": round(centroid, 1),
#         "onset_rate": round(onset_rate, 2),
#         "plot": buf,
#     }
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile -a app.py
# 
# # ─────────────────────────────────────────────
# # SIDEBAR — Dog Profile
# # ─────────────────────────────────────────────
# with st.sidebar:
#     st.markdown("## 🐾 Dog Profile")
#     st.markdown("---")
# 
#     dog_breed = st.selectbox("Breed", [
#         "Labrador Retriever", "Golden Retriever", "German Shepherd",
#         "Bulldog", "Poodle", "Beagle", "Corgi", "Husky",
#         "Border Collie", "Dachshund", "Shiba Inu", "Mixed breed"
#     ])
#     dog_color = st.selectbox("Coat Color", [
#         "golden", "black", "white", "brown", "red",
#         "gray", "cream", "spotted black and white", "tricolor"
#     ])
#     dog_age = st.selectbox("Age", [
#         "8-week-old puppy", "3-month-old puppy", "6-month-old puppy",
#         "1-year-old young dog", "adult dog", "senior dog"
#     ])
#     trainer = st.selectbox("Trainer Appearance", [
#         "adult woman", "adult man", "young woman", "young man"
#     ])
#     environment = st.selectbox("Training Environment", [
#         "sunny grass field outdoors",
#         "indoor wooden floor living room",
#         "suburban backyard",
#         "park with trees",
#         "beach",
#     ])
#     command = st.selectbox("Command to Train", list(COMMAND_STANDARDS.keys()))
# 
#     st.markdown("---")
#     st.caption("PawCoach uses science-based standards from animal behavior research (Pryor 2009, Hiby et al. 2004) to evaluate your training voice.")
#

# Commented out IPython magic to ensure Python compatibility.
# 
# %%writefile -a app.py
# 
# # ─────────────────────────────────────────────
# # MAIN AREA
# # ─────────────────────────────────────────────
# st.markdown("# 🐾 PawCoach")
# st.markdown("#### AI-Powered Dog Training Assistant")
# st.markdown("---")
# 
# tab1, tab2, tab3 = st.tabs([
#     "📸  Training Visual Guide",
#     "🎙️  Voice Command Analyzer",
#     "🐶  Bark Emotion Recognizer",
# ])
# 
# # ══════════════════════════════════════════════
# # TAB 1 — IMAGE GENERATION
# # ══════════════════════════════════════════════
# with tab1:
#     st.markdown("### 📸 4-Step Visual Training Guide")
#     st.markdown(
#         f"Generate a photo-realistic 4-panel training guide for teaching your "
#         f"**{dog_breed}** the **{command}** command."
#     )
# 
#     col_btn, col_info = st.columns([1, 3])
#     with col_btn:
#         gen_button = st.button("🎨 Generate Guide", key="gen_images")
#     with col_info:
#         st.info("⏱️ Generation takes ~2–3 minutes on a free Colab GPU. Please be patient.")
# 
#     if gen_button:
#         with st.spinner("Loading Stable Diffusion model (first run takes ~15s)..."):
#             pipe = load_sd_pipeline()
# 
#         prompts = build_prompts(dog_breed, dog_color, trainer, environment, command)
#         images = []
#         progress = st.progress(0, text="Generating panels...")
# 
#         for i in range(1, 5):
#             seed = 42 + i * 13
#             with st.spinner(f"Generating {PANEL_LABELS[i]}..."):
#                 img = generate_panel(pipe, prompts[i], seed)
#                 images.append(img)
#             progress.progress(i / 4, text=f"Done: {PANEL_LABELS[i]}")
#             time.sleep(3)
# 
#         # Display individual panels with labels
#         cols = st.columns(4)
#         for i, (col, img) in enumerate(zip(cols, images)):
#             with col:
#                 st.markdown(f'<div class="panel-label">{PANEL_LABELS[i+1]}</div>', unsafe_allow_html=True)
#                 st.image(img, use_column_width=True)
# 
#         # Grid download
#         grid = make_grid(images)
#         buf = io.BytesIO()
#         grid.save(buf, format="PNG")
#         buf.seek(0)
#         st.download_button(
#             "⬇️ Download Full Grid",
#             data=buf,
#             file_name=f"pawcoach_{dog_breed.lower().replace(' ','_')}_{command.lower()}_guide.png",
#             mime="image/png",
#         )
# 
#         # Show prompts used
#         with st.expander("🔍 View prompts used"):
#             for pid, p in prompts.items():
#                 st.markdown(f"**{PANEL_LABELS[pid]}:** {p}")
# 
# # ══════════════════════════════════════════════
# # TAB 2 — VOICE COMMAND ANALYZER
# # ══════════════════════════════════════════════
# with tab2:
#     st.markdown("### 🎙️ Voice Command Analyzer")
#     st.markdown(
#         "Record yourself saying the command word. "
#         "PawCoach will analyze your voice against science-based standards "
#         "for effective dog training communication."
#     )
# 
#     std_info = COMMAND_STANDARDS[command]
#     with st.container():
#         st.markdown('<div class="pawcard">', unsafe_allow_html=True)
#         st.markdown(f"**Science Standards for: `{command}`**")
#         c1, c2, c3 = st.columns(3)
#         c1.metric("Max Duration", f"{std_info['duration_max']}s", help="Short commands are clearer for dogs")
#         c2.metric("Min Volume", f"{std_info['volume_min']} dB", help="Assertive tone gets attention")
#         c3.metric("Pitch Contour", "Must drop ↘" if std_info["pitch_drop"] else "Neutral / rising OK ↗",
#                   help="Rising pitch sounds like a question to dogs")
#         st.markdown('</div>', unsafe_allow_html=True)
# 
#     st.markdown("---")
#     st.markdown("#### 🔴 Record Your Command")
#     st.markdown(f"Say **\"{command}\"** clearly into your microphone:")
# 
#     audio_bytes_voice = audio_recorder(
#         text="Click to record",
#         recording_color="#e74c3c",
#         neutral_color="#2ecc71",
#         icon_name="microphone",
#         icon_size="2x",
#         pause_threshold=2.0,
#         key="voice_recorder",
#     )
# 
#     if audio_bytes_voice:
#         st.audio(audio_bytes_voice, format="audio/wav")
#         with st.spinner("Analyzing your voice command..."):
#             analysis = analyze_voice(audio_bytes_voice, command)
# 
#         if analysis is None:
#             st.error("Could not process audio. Please try recording again.")
#         else:
#             st.markdown("---")
#             st.markdown("#### 📊 Analysis Results")
# 
#             # Score display
#             score = analysis["score"]
#             score_color = "#2ecc71" if score >= 75 else "#f39c12" if score >= 50 else "#e74c3c"
#             grade = "Excellent" if score >= 75 else "Needs Work" if score >= 50 else "Try Again"
# 
#             col_score, col_metrics = st.columns([1, 3])
#             with col_score:
#                 st.markdown(f"""
#                 <div class="score-box">
#                     <div class="score-num" style="color:{score_color}">{score}</div>
#                     <div style="color:#aaa; font-size:0.85rem;">/ 100</div>
#                     <div style="color:{score_color}; font-weight:700; margin-top:4px">{grade}</div>
#                 </div>
#                 """, unsafe_allow_html=True)
# 
#             with col_metrics:
#                 for dim, data in analysis["results"].items():
#                     icon = "✅" if data["pass"] else ("⚠️" if dim != "clarity" else "❌")
#                     with st.expander(f"{icon} {dim.capitalize()} — {'Pass' if data['pass'] else 'Fail'}"):
#                         st.markdown(data["feedback"])
#                         st.caption(f"Measured: `{data['value']}` | Target: `{data['target']}`")
# 
#             # Waveform + Pitch plot
#             st.markdown("#### 📈 Audio Visualization")
#             st.image(analysis["plot"], use_column_width=True)
# 
#             # Overall coaching tip
#             st.markdown("---")
#             if score >= 75:
#                 st.success("🎉 Great command delivery! Consistent use of this voice pattern will reinforce learning for your dog.")
#             elif score >= 50:
#                 st.warning("💪 Good effort! Focus on the failed dimensions above and try again.")
#             else:
#                 st.error("🔄 Keep practicing! Dogs respond best to short, firm, and clearly enunciated commands.")
# 
# # ══════════════════════════════════════════════
# # TAB 3 — BARK EMOTION RECOGNIZER
# # ══════════════════════════════════════════════
# with tab3:
#     st.markdown("### 🐶 Bark Emotion Recognizer")
#     st.markdown(
#         "Record your dog's bark **and** tell us the context. "
#         "PawCoach combines acoustic analysis with situational context "
#         "for a more accurate emotional reading."
#     )
# 
#     st.markdown("#### 1️⃣ Describe the Context")
#     context_options = {
#         "excitement": "🎾 Before play / walk / feeding",
#         "alert":      "🔔 Stranger nearby / doorbell / new object",
#         "distress":   "😟 Alone / confined / in pain",
#         "play":       "🏃 During active play with you",
#         "calm":       "😴 Quiet time / no obvious trigger",
#     }
#     context_display = st.radio(
#         "What was happening when your dog barked?",
#         options=list(context_options.keys()),
#         format_func=lambda k: context_options[k],
#         horizontal=True,
#     )
# 
#     st.markdown("---")
#     st.markdown("#### 2️⃣ Record the Bark")
#     st.markdown("Play back a bark your dog made (or hold phone near dog and record live):")
# 
#     audio_bytes_bark = audio_recorder(
#         text="Click to record bark",
#         recording_color="#e74c3c",
#         neutral_color="#3498db",
#         icon_name="dog",
#         icon_size="2x",
#         pause_threshold=3.0,
#         key="bark_recorder",
#     )
# 
#     if audio_bytes_bark:
#         st.audio(audio_bytes_bark, format="audio/wav")
#         with st.spinner("Analyzing bark acoustics + context..."):
#             bark_result = analyze_bark(audio_bytes_bark, context_display)
# 
#         if bark_result is None:
#             st.error("Could not process audio. Please try again.")
#         else:
#             st.markdown("---")
#             st.markdown("#### 🎯 Emotion Reading")
# 
#             conf_color = {
#                 "High": "#2ecc71",
#                 "Medium": "#f39c12",
#                 "Low": "#e74c3c",
#             }.get(bark_result["confidence"], "#aaa")
# 
#             col_e, col_d = st.columns([1, 2])
#             with col_e:
#                 st.markdown(f"""
#                 <div class="score-box" style="border-color:{conf_color}">
#                     <div style="font-size:2.2rem">{bark_result['emotion']}</div>
#                     <div style="color:{conf_color}; font-weight:700; margin-top:8px">
#                         {bark_result['confidence']} Confidence
#                     </div>
#                 </div>
#                 """, unsafe_allow_html=True)
# 
#             with col_d:
#                 st.markdown("**🎙️ Acoustic Features Detected:**")
#                 st.markdown(f"- Frequency profile: `{bark_result['acoustic_cluster'].replace('_', ' ').title()}`")
#                 st.markdown(f"- Spectral centroid: `{bark_result['centroid_hz']} Hz`")
#                 st.markdown(f"- Bark onset rate: `{bark_result['onset_rate']} bursts/sec`")
#                 st.markdown(f"- Context provided: `{context_options[context_display]}`")
# 
#             st.markdown("---")
#             st.markdown("#### 💡 Trainer Advice")
#             st.info(bark_result["advice"])
# 
#             st.markdown("#### 📊 Acoustic Visualization")
#             st.image(bark_result["plot"], use_column_width=True)
# 
#             st.caption(
#                 "Note: This analysis combines acoustic features with contextual signals. "
#                 "Results are indicative, not diagnostic. Always consult a certified animal "
#                 "behaviorist for concerning behavior patterns."
#             )

!pkill -f streamlit

import subprocess
import time
import re

# ── Install cloudflared (Run once per session) ──────────────────
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared

# ── Terminate old processes ────────────────────────────────────
subprocess.run(["pkill", "-f", "streamlit"], capture_output=True)
subprocess.run(["pkill", "-f", "cloudflared"], capture_output=True)
time.sleep(2)

# ── Start Streamlit ─────────────────────────────────────────────
proc = subprocess.Popen(
    ["streamlit", "run", "app.py",
     "--server.port=8501",
     "--server.headless=true",
     "--server.enableCORS=false",
     "--server.enableXsrfProtection=false"],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
)
time.sleep(5)

# ── Start cloudflared tunnel ────────────────────────────────────
tunnel = subprocess.Popen(
    ["./cloudflared", "tunnel", "--url", "http://localhost:8501"],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
)

# ── Wait and extract the public URL ──────────────────────────────
print("⏳ Establishing tunnel, please wait...")
public_url = None
for _ in range(30):
    line = tunnel.stdout.readline().decode("utf-8", errors="ignore")
    match = re.search(r'https://[a-z0-9\-]+\.trycloudflare\.com', line)
    if match:
        public_url = match.group(0)
        break
    time.sleep(1)

if public_url:
    print("=" * 60)
    print("🐾 PawCoach is LIVE!")
    print(f"   👉 Open this link: {public_url}")
    print("=" * 60)
    print("（Keep this cell running. Stopping the cell will close the application.）")
else:
    print("❌ Failed to establish the tunnel. Please re-run this cell.")

# Run this cell ONLY when you want to shut everything down.

# from pyngrok import ngrok
# import subprocess

# ngrok.disconnect(public_url)
# ngrok.kill()
# subprocess.run(["pkill", "-f", "streamlit"], capture_output=True)
# print("✅ PawCoach shut down.")